export const DEFAULT_TIMER_MINUTES = 25
export const TIMER_MAX_MINUTES = 60
export const TIMER_SNAP_MINUTES = 1
export const QUICK_TIMER_MINUTES = [5, 15, DEFAULT_TIMER_MINUTES, 50]
export const DEFAULT_TIMER_SECONDS = DEFAULT_TIMER_MINUTES * 60
